### ISSUE TITLE
SPO extraction is broken

### ISSUE THREAD

**Issue by chiaragambirasio** [neuland-ingolstadt/neuland.app#122]
Had to realize that I can't see my great average grade... Hope someone competent can fix it 😶‍🌫️ @M4GNV5

**Comment by alexhorn** [comment]
`spo-grade-weights.json` is empty in the built container:

```
alex@nlsrv01:/mnt/docker-apps/neuland.app$ sudo docker-compose exec app bash
node@0db37042ef0f:/opt/next$ cd data
node@0db37042ef0f:/opt/next/data$ cat spo-grade-weights.json
{}
```

When you rebuild the container, the SPO extraction appears to be broken:
```
Step 5/27 : RUN ./run_extraction.sh
 ---> Running in 4260447b7e36
Handling path satzungen-business-school
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
No appendix found for
Creating file SPOs/.pdf
Handling path satzungen-fakultaet-elektro-und-informationstechnik
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
No appendix found for
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Handling path satzungen-fakultaet-informatik
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Handling path satzungen-fakultaet-maschinenbau
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Handling path satzungen-fakultaet-wirtschaftsingenieurwesen
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Handling path satzungen-campus-neuburg
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Handling path satzungen-studienfakultaet-iaw
No appendix found for
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
No appendix found for
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Creating file SPOs/.pdf
Analyzing SPOs/*.pdf => weightings/*.json
Traceback (most recent call last):
  File "/opt/extract_grade_weighting.py", line 19, in <module>
    tables = camelot.read_pdf(sys.argv[1], pages="all")
  File "/usr/local/lib/python3.10/site-packages/camelot/io.py", line 111, in read_pdf
    p = PDFHandler(filepath, pages=pages, password=password)
  File "/usr/local/lib/python3.10/site-packages/camelot/handlers.py", line 50, in __init__
    self.pages = self._get_pages(pages)
  File "/usr/local/lib/python3.10/site-packages/camelot/handlers.py", line 74, in _get_pages
    with open(self.filepath, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'SPOs/*.pdf'
```

**Comment by chiaragambirasio** [comment]
Still broken :( @M4GNV5

**Comment by M4GNV5** [comment]
Did you test it on dev.neuland.app? For me it works there, we just did not push it to production yet.

[The diff between develop and main](https://github.com/neuland-ingolstadt/neuland.app/compare/master...develop?expand=1) doesnt seem to include any breaking changes right now, it does however include a major refactor. Do you think it is safe to merge it @alexhorn?

**Comment by alexhorn** [comment]
Should be safe to merge, however for me it doesn't work on dev either

**Comment by M4GNV5** [comment]
As you can see in the following (definitly not manipulated) screenshot the grades now also work on https://neuland.app again :smile: 

![image](https://user-images.githubusercontent.com/5504713/160281668-c33bbb19-bdb4-4bb4-940b-f3a2b0210fe4.png)
